version: '3'
services:
  backend:
    container_name: backoffice-laravel
    tty: true
    restart: unless-stopped
    ports:
      - "8000:80"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    container_name: backoffice-db
    image: mysql:8
    tty: true
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=feeluy
    volumes:
      - ./mysql-data:/var/lib/mysql
   