name: UseImageBackendBackoffice
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Actualizar imagen
        run: |
          docker pull marrzuy/backoffice-backend:latest
      - name: Detenes contenedores
        run: |
          cd /var/www/html/Arquitectura-de-Backoffice
          docker compose down
      - name: Iniciar contenedores
        run: |
          cd /var/www/html/Arquitectura-de-Backoffice
          docker compose up -d
      - name: Generarndo Key
        run: |   
            docker exec -i backoffice-backend php artisan key:generate
      - name: Optimizando
        run: | 
            docker exec -i backoffice-backend php artisan optimize